# -*- coding: utf-8 -*-
"""Driver-Based-Financial-Modeling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J6OIiQYWCGN0mRQvdVnnti_nZ8BvosUS
"""

# 1. Import Required Libraries

import numpy as np
import pandas as pd

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Display options
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

# Machine Learning
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# Metrics
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

# 2. Load Dataset

df = pd.read_csv("/content/Income Survey Dataset.csv")

print("Dataset Loaded Successfully!")

#first few rows of data

df.head()

# Rows and Column count

print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

df.shape

#Column names

df.columns

#Dataset information

df.info()

"""# ****EDA****"""

#Data Statistics summary

df.describe()

#Checking missing values

missing_values = df.isnull().sum()
missing_values = missing_values[missing_values > 0]
missing_values.sort_values(ascending=False)

#Checking for Duplicates

print("Duplicate rows :", df.duplicated().sum())

#If there are any duplicates, to remove those
#df = df.drop_duplicates()

#Plotting Target Variable
plt.figure(figsize=(8,5))
sns.histplot(df["income_after_tax"], bins=40, kde=True)
plt.title("Distribution of Income_After_Tax")
plt.show()

"""- The large bar on the left (near 0–100,000) represents people with realistic after-tax incomes.
- The large bar on the far right (at 100,000,000) represents records with the value 100,000,000.

Income is right Skewed
"""

plt.figure(figsize=(8,6))
sns.boxplot(x=df["income_after_tax"])
plt.show()

#Correlation
numeric = df.select_dtypes(include=np.number)
corr = numeric.corr()
plt.figure(figsize=(8,6))
sns.heatmap(corr, cmap="coolwarm",center=0)
plt.title("Correlation Matrix")
plt.show()

"""Variables like:
- Cap_gain
- Child_benefit
- Earning
- Investment
- Private_pension

are all very strongly correlated with one another.

  **Why?**

These are all income-related variables.

- For example:

  - Higher earners often have higher investments.
  - Higher earners may contribute more to pensions.
  - Capital gains tend to be larger for wealthier individuals.

- Total_income and Salary_wages

These show strong positive correlations with other income variables.

  - That makes sense because:

  Salary_wages
        ↓
  Earning
        ↓
  Total_income
        ↓
  income_after_tax

These variables are mathematically related

You can see several blue cells involving Age_gap.

This indicates negative correlations with some variables.

Possible interpretation:

- Younger individuals may have fewer years of work.
- Younger respondents may have lower pension income.
- Younger respondents may have lower total earnings.

Variables to use carefully

These are closely related to the target:

- Total_income
- Salary_wages
- Earning
- Pension
- Investment
- Cap_gain
"""

#Target Correlation
corr_target = corr["income_after_tax"].sort_values(ascending=False)
print(corr_target)

"""***Data Cleaning***"""

#Remove Identifier

#PERSONID is just an identifier and should not be used for prediction.
df.drop("PersonID", axis=1, inplace=True)

# Handling missing values
numeric_cols = df.select_dtypes(include=np.number).columns

for col in numeric_cols:
  df[col] = df[col].fillna(df[col].median())

"""Separate Features and Target"""

X = df.drop("income_after_tax", axis = 1)
Y = df["income_after_tax"]

"""Train Test Split"""

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

Scaler = StandardScaler()

X_train_scaled = Scaler.fit_transform(X_train)
X_test_scaled = Scaler.fit_transform(X_test)

"""Before building the model: some variables in the dataset (such as Total_income, Salary_wages, Earning, and possibly other income components) may directly determine income_after_tax. If we include them without careful thought, the model may suffer from data leakage, producing unrealistically high accuracy.

**Data Preparation & Model Building**:
"""

# Remove data leakage variables
# For the first model (Socioeconomic Model), we'll exclude these variables:
leakage_columns = [
    "income_after_tax",      # Target
    "Total_income",
    "Salary_wages",
    "Earning",
    "Self_emp_income",
    "Investment",
    "Cap_gain",
    "Pension",
    "Old_age_pension",
    "Guaranteed_income",
    "Emp_insurance",
    "compensation",
    "Child_benefit"
]

X = df.drop(columns=leakage_columns)

y = df["income_after_tax"]

print(X.columns)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20,random_state=42)

print("Training samples :", X_train.shape[0])
print("Testing samples  :", X_test.shape[0])

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

#Model 1 - Linear Regression
from sklearn.linear_model import LinearRegression

linear_model = LinearRegression()

linear_model.fit(X_train_scaled, y_train)

linear_pred = linear_model.predict(X_test_scaled)

from sklearn.metrics import (mean_absolute_error,mean_squared_error, r2_score)

linear_mae = mean_absolute_error(y_test, linear_pred)

linear_rmse = mean_squared_error(y_test,linear_pred)

linear_r2 = r2_score(y_test,linear_pred)

print("Linear Regression")
print("-------------------------")
print("MAE :", linear_mae)
print("RMSE:", linear_rmse)
print("R²  :", linear_r2)

#Model 2 : Ridge Regression
from sklearn.linear_model import Ridge

ridge = Ridge(alpha=1.0)

ridge.fit(X_train_scaled, y_train)

ridge_pred = ridge.predict(X_test_scaled)

ridge_mae = mean_absolute_error(y_test, ridge_pred)

ridge_rmse = mean_squared_error(y_test,ridge_pred,)

ridge_r2 = r2_score(y_test,ridge_pred)

print("Ridge Regression")
print("-------------------------")
print("MAE :", ridge_mae)
print("RMSE:", ridge_rmse)
print("R²  :", ridge_r2)

#Model 3 : Lasso Regression
from sklearn.linear_model import Lasso

lasso = Lasso(alpha=0.1)

lasso.fit(X_train_scaled, y_train)

lasso_pred = lasso.predict(X_test_scaled)

lasso_mae = mean_absolute_error(y_test, lasso_pred)

lasso_rmse = mean_squared_error(y_test,lasso_pred)

lasso_r2 = r2_score(y_test,lasso_pred)

print("Lasso Regression")
print("-------------------------")
print("MAE :", lasso_mae)
print("RMSE:", lasso_rmse)
print("R²  :", lasso_r2)

#Model 4 : Random Forest Regression
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=300,random_state=42,n_jobs=-1)

rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)

rf_mae = mean_absolute_error(y_test, rf_pred)

rf_rmse = mean_squared_error(y_test,rf_pred,)

rf_r2 = r2_score(y_test,rf_pred)

print("Random Forest")
print("-------------------------")
print("MAE :", rf_mae)
print("RMSE:", rf_rmse)
print("R²  :", rf_r2)

#Comparing all models

results = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Ridge Regression",
        "Lasso Regression",
        "Random Forest"
    ],
    "MAE": [
        linear_mae,
        ridge_mae,
        lasso_mae,
        rf_mae
    ],
    "RMSE": [
        linear_rmse,
        ridge_rmse,
        lasso_rmse,
        rf_rmse
    ],
    "R2 Score": [
        linear_r2,
        ridge_r2,
        lasso_r2,
        rf_r2
    ]
})

results = results.sort_values("R2 Score", ascending=False)

print(results)

"""###Model Evaluation, Interpretation & Deployment

Actual vs Predicted Plot
"""

import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))

plt.scatter(y_test, rf_pred, alpha=0.6)

plt.plot(
    [y_test.min(), y_test.max()],
    [y_test.min(), y_test.max()],
    color='red',
    linewidth=2
)

plt.xlabel("Actual Income After Tax")
plt.ylabel("Predicted Income After Tax")
plt.title("Actual vs Predicted (Random Forest)")

plt.show()

#Residual Analysis
residuals = y_test - rf_pred

plt.figure(figsize=(8,5))

plt.hist(residuals, bins=40)

plt.title("Distribution of Residuals")
plt.xlabel("Residual")
plt.ylabel("Frequency")

plt.show()

#Residual Scalar Plot
plt.figure(figsize=(8,5))

plt.scatter(rf_pred, residuals, alpha=0.5)

plt.axhline(0, color='red')

plt.xlabel("Predicted Values")
plt.ylabel("Residuals")

plt.title("Residual Plot")

plt.show()

#Feature Importance
importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

importance.head(20)

top20 = importance.head(20)

plt.figure(figsize=(10,8))

plt.barh(top20["Feature"], top20["Importance"])

plt.xlabel("Importance")

plt.title("Top 20 Important Features")

plt.gca().invert_yaxis()

plt.show()

#Linear Regression Coefficients
coef = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": linear_model.coef_
})

coef = coef.sort_values(
    by="Coefficient",
    ascending=False
)

coef.head(20)

coef.tail(20)

#Save the best model
import joblib

joblib.dump(rf, "Income_Model.pkl")

print("Model Saved Successfully")

joblib.dump(scaler, "Scaler.pkl")

loaded_model = joblib.load("Income_Model.pkl")

prediction = loaded_model.predict(X_test)

prediction[:10]

results

"""Random Forest achieved the highest predictive performance among the evaluated models.
Linear models provided interpretable relationships between socioeconomic factors and after-tax income.
Feature importance identified the strongest predictors of after-tax income.
The final model can estimate after-tax income for new individuals based on demographic, education, employment, and household characteristics.

Use one-hot encoding (OneHotEncoder) instead of LabelEncoder for categorical variables like Province and Marital_status. Label encoding imposes an artificial order that can affect linear models.
Use survey weights (Weight) if your objective is inference about the population rather than just prediction. This is particularly important for survey datasets.
Perform hyperparameter tuning for the Random Forest using GridSearchCV or RandomizedSearchCV to optimize parameters such as n_estimators, max_depth, and min_samples_leaf.
Use cross-validation (e.g., 5-fold) when comparing models to obtain more reliable performance estimates.
Add SHAP explainability. SHAP values provide both global and local explanations and are widely used in industry for interpreting complex models.
"""